### ISSUE TITLE
Suggestion: Faster droprate

### ISSUE THREAD

**Issue by ghost** [syldium/NetherTree#1]
Can you make it so that we can configure how fast the leaves will decay?
This would make this plugin 100% perfect for me.

**Comment by syldium** [comment]
Hi, thanks for your suggestion! The decay speed is currently calculated based on the `randomTickSpeed` gamerule, but it would indeed be interesting to be able to override this value.

**Comment by ghost** [comment]
This is not entirely true.
When i change my randomTickSpeed gamerule to 3000, it drops just as fast with my randomTickSpeed gamerule to 3.

**Comment by ghost** [comment]
<3
